name: apiverve_interestrate
description: Interest Rate is a tool for retrieving current central bank policy interest rates for major economies worldwide. It returns the latest rate along with the central bank name and effective date.
version: 1.1.14
homepage: https://apiverve.com/marketplace/interestrate?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/interestrate-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
